In [18]:
%matplotlib notebook

import pandas
import matplotlib

In [19]:
df = pandas.read_csv("usage.csv.gz")

In [25]:

df.plot(x='DATE',y='USAGE')

ValueError: scatter requires x column to be numeric

In [10]:
df

                 TYPE        DATE START TIME END TIME  USAGE UNITS NOTES
0      Electric usage  2016-01-01      00:00    00:59   0.72   kWh   NaN
1      Electric usage  2016-01-01      01:00    01:59   0.69   kWh   NaN
2      Electric usage  2016-01-01      02:00    02:59   0.71   kWh   NaN
3      Electric usage  2016-01-01      03:00    03:59   2.53   kWh   NaN
4      Electric usage  2016-01-01      04:00    04:59   0.80   kWh   NaN
5      Electric usage  2016-01-01      05:00    05:59   0.71   kWh   NaN
6      Electric usage  2016-01-01      06:00    06:59   0.79   kWh   NaN
7      Electric usage  2016-01-01      07:00    07:59   1.38   kWh   NaN
8      Electric usage  2016-01-01      08:00    08:59   0.91   kWh   NaN
9      Electric usage  2016-01-01      09:00    09:59  -0.29   kWh   NaN
10     Electric usage  2016-01-01      10:00    10:59  -0.72   kWh   NaN
11     Electric usage  2016-01-01      11:00    11:59  -0.48   kWh   NaN
12     Electric usage  2016-01-01      12:00    12:59  -0.09   kWh   NaN
13     Electric usage  2016-01-01      13:00    13:59   0.30   kWh   NaN
14     Electric usage  2016-01-01      14:00    14:59   0.57   kWh   NaN
15     Electric usage  2016-01-01      15:00    15:59   0.41   kWh   NaN
16     Electric usage  2016-01-01      16:00    16:59   0.67   kWh   NaN
17     Electric usage  2016-01-01      17:00    17:59   1.82   kWh   NaN
18     Electric usage  2016-01-01      18:00    18:59   3.99   kWh   NaN
19     Electric usage  2016-01-01      19:00    19:59   1.36   kWh   NaN
20     Electric usage  2016-01-01      20:00    20:59   1.33   kWh   NaN
21     Electric usage  2016-01-01      21:00    21:59   1.26   kWh   NaN
22     Electric usage  2016-01-01      22:00    22:59   1.05   kWh   NaN
23     Electric usage  2016-01-01      23:00    23:59   0.91   kWh   NaN
24     Electric usage  2016-01-02      00:00    00:59   0.65   kWh   NaN
25     Electric usage  2016-01-02      01:00    01:59   0.50   kWh   NaN
26     Electric usage  2016-01-02      02:00    02:59   0.50   kWh   NaN
27     Electric usage  2016-01-02      03:00    03:59   2.47   kWh   NaN
28     Electric usage  2016-01-02      04:00    04:59   0.63   kWh   NaN
29     Electric usage  2016-01-02      05:00    05:59   0.59   kWh   NaN
...               ...         ...        ...      ...    ...   ...   ...
13576  Electric usage  2017-07-20      18:00    18:59   1.55   kWh   NaN
13577  Electric usage  2017-07-20      19:00    19:59   3.31   kWh   NaN
13578  Electric usage  2017-07-20      20:00    20:59   4.17   kWh   NaN
13579  Electric usage  2017-07-20      21:00    21:59   4.00   kWh   NaN
13580  Electric usage  2017-07-20      22:00    22:59   2.26   kWh   NaN
13581  Electric usage  2017-07-20      23:00    23:59   0.71   kWh   NaN
13582  Electric usage  2017-07-21      00:00    00:59   0.76   kWh   NaN
13583  Electric usage  2017-07-21      01:00    01:59   0.42   kWh   NaN
13584  Electric usage  2017-07-21      02:00    02:59   2.68   kWh   NaN
13585  Electric usage  2017-07-21      03:00    03:59   2.24   kWh   NaN
13586  Electric usage  2017-07-21      04:00    04:59   0.66   kWh   NaN
13587  Electric usage  2017-07-21      05:00    05:59   0.54   kWh   NaN
13588  Electric usage  2017-07-21      06:00    06:59   0.09   kWh   NaN
13589  Electric usage  2017-07-21      07:00    07:59  -1.08   kWh   NaN
13590  Electric usage  2017-07-21      08:00    08:59  -2.02   kWh   NaN
13591  Electric usage  2017-07-21      09:00    09:59  -2.88   kWh   NaN
13592  Electric usage  2017-07-21      10:00    10:59  -3.16   kWh   NaN
13593  Electric usage  2017-07-21      11:00    11:59  -3.10   kWh   NaN
13594  Electric usage  2017-07-21      12:00    12:59  -2.90   kWh   NaN
13595  Electric usage  2017-07-21      13:00    13:59  -2.97   kWh   NaN
13596  Electric usage  2017-07-21      14:00    14:59  -2.08   kWh   NaN
13597  Electric usage  2017-07-21      15:00    15:59  -1.40   kWh   NaN
13598  Electric usage  2017-07-21      16:00    16:59   0.50   kWh   NaN
13599  Electric usage  2017-07-21      17:00    17:59   2.79   kWh   NaN
13600  Electric usage  2017-07-21      18:00    18:59   2.22   kWh   NaN
13601  Electric usage  2017-07-21      19:00    19:59   4.23   kWh   NaN
13602  Electric usage  2017-07-21      20:00    20:59   4.69   kWh   NaN
13603  Electric usage  2017-07-21      21:00    21:59   3.83   kWh   NaN
13604  Electric usage  2017-07-21      22:00    22:59   2.60   kWh   NaN
13605  Electric usage  2017-07-21      23:00    23:59   0.61   kWh   NaN

[13606 rows x 7 columns]